// The model report card — every model DRAMATIS runs, evaluated, or rejected,
// with the evidence for each grade. This feeds the Studio's Models view.
//
// RULES OF THIS FILE:
//   - Every grade carries its WHY, and the why must be traceable to a
//     measurement, a licence file that was read, or an ear ruling — not vibes.
//   - Rejected candidates STAY in the table. "We tested X and it lost" is as
//     valuable as "we use Y", and it stops the next person re-evaluating them.
//   - measured[] entries say what was measured ON THIS PROJECT's hardware and
//     corpus. Paper numbers live in the notes, clearly attributed.
// Deeper detail: docs/MODELS.md. Live speeds are merged in by /api/models from
// Quick Narrate history and benchmark output at request time.

export const GRADE_RANK = { 'A': 12, 'A-': 11, 'B+': 10, 'B': 9, 'B-': 8, 'C+': 7, 'C': 6, 'C-': 5, 'D': 4, 'F': 1, '—': 0 };

export const MODEL_FACTS = [
  {
    id: 'kokoro', name: 'Kokoro-82M', kind: 'voice', tier: 'free · local CPU',
    status: 'active', grade: 'A-',
    gradeWhy: 'Best free narration per watt in the field (survey 2026-07: no successor exists). Docked for an uneven catalog — af_heart is an A voice, am_adam an F+ — and zero direction control.',
    licence: 'Apache-2.0 (code + weights). GPL espeak chain in the Python dep — use fine, redistribution not.',
    cost: '$0',
    role: 'Narration — the tireless default narrator lane.',
    speedStatic: '≈70 chars/s on CPU (0.014 s/char measured); RTF 0.22–0.31',
    caps: '509 phonemes/call HARD (crashes, not truncates) — chunked by phoneme budget since 2026-07-20',
    capabilities: ['54 voices with published quality grades', 'voice BLENDING (weighted style vectors, verified deterministic)', 'IPA pronunciation override (is_phonemes) for character names', 'speed 0.5–2.0'],
    limitations: ['no emotion/direction control at all', 'no pitch control (graph takes tokens/style/speed only)', 'ALL CAPS, newlines do nothing — measured bit-identical'],
    measured: ['digit runs hit 8.2 phonemes/char vs 1.0 for prose — the old char-budget chunker CRASHED on phone numbers/years/numerals (fixed, verified on 4 hostile inputs)', 'spaced hyphen " - " produces NO pause; punctuation presence triples pauses (0.045→0.13s) but the specific mark barely matters'],
    earRuling: 'bm_george carried every early book; catalog grades hold up.',
  },
  {
    id: 'qwen3', name: 'Qwen3-TTS-1.7B', kind: 'voice', tier: 'free · local GPU',
    status: 'active', grade: 'B+',
    gradeWhy: 'Free unlimited character voices + cloning is the economic engine of the whole company model. Docked: instruct is DEAD on clones (upstream-confirmed), ~20% clone drift needs the register gate, and VoiceDesign is weak on age.',
    licence: 'Apache-2.0 (code + weights, verified — no Tongyi extras).',
    cost: '$0',
    role: 'Character voices: design new ones, clone company actors, unlimited free lines.',
    speedStatic: 'batches of 8 on GPU; ~5–8 GB VRAM',
    caps: '~11,000 chars/call real ceiling (8192 frames @ 12.5 Hz = 655 s audio); registry holds 6,000 because one runaway line stalls its whole batch',
    capabilities: ['VoiceDesign from a sentence (12-field official schema)', 'cloning from 8–15 s refs (ref_text raises similarity 0.75→0.89)', 'CustomVoice: the ONE mode with preset timbre + per-line instruct', '9 presets (only Ryan/Aiden are English, both male)'],
    limitations: ['instruct silently dropped on the clone path — per-line emotion on clones is impossible', 'runaway generation on exotic characters (~0.5% random EOS failure)', 'age/accent weak in design — route hero age/accent to premium'],
    measured: ['register gate: female >170 Hz / male <150 Hz, gates design + cached refs + clone output; regiment 8/8 pass in 244 s', 'clone gender drift ~20% of requests (upstream) — gate re-roll usually lands'],
    earRuling: 'NOLA clone: "sounds like a Black lady, older — really really good." Liu redo verified.',
  },
  {
    id: 'gemini', name: 'Gemini 3.1 Flash TTS', kind: 'voice', tier: 'paid · API (Replicate)',
    status: 'active', grade: 'A',
    gradeWhy: 'Robert\'s #1 for characterful voices — the only engine that takes a director\'s note as first-class input. Multi-speaker measured working (labels not spoken, registers 108 Hz apart). Cheap for what it does.',
    licence: 'API service; output usable commercially.',
    cost: '$0.00129/s of audio ≈ $0.077/min ≈ $4.64/finished-hr (measured token billing)',
    role: 'Directed character performances; seeds for the company; accent work via 87 locales.',
    speedStatic: '~7 s/line typical; 600 predictions/min ceiling',
    caps: 'text ≤4,000 bytes + prompt ≤4,000 bytes (HARD failure past it, no truncation) — chunked; ~655 s output/call',
    capabilities: ['free-text director\'s note (style, pace, age, accent, delivery)', 'multi-speaker in one call via labeled text (measured: real turn-taking)', '87 language_code locales = free accent leverage', '30 fixed voices; 4 carry age/texture signal (Leda/Gacrux/Algenib/Enceladus)'],
    limitations: ['NO custom voices, ever (closed enum) — permanence requires cloning the seed into Qwen3', 'adjective bracket tags get SPOKEN ALOUD (mode 3) — emotion must ride in the prompt', 'register drifts within long multi-speaker calls (~27 Hz measured)'],
    measured: ['duration gate: legit delivery 0.9–2.1×, direction-read-aloud fault 3.8–6.2× — re-rolls then refuses', 'phrasing law: "This line is <adj> — <detail>" measured 0.99× vs 3.83× for a deviant opener', 'a 3,900-byte director\'s note costs only ~$9.75 across a 5,000-line book — spend bytes on quality'],
    earRuling: '"I like the Gemini one better… really got her talking like she\'s from New Orleans." #1.',
  },
  {
    id: 'elevenlabs', name: 'ElevenLabs (v3 / v2 family)', kind: 'voice', tier: 'paid · API',
    status: 'active', grade: 'A-',
    gradeWhy: 'Premium acting and the narrator Robert chose by blind ear test. Docked: v3 silently ignores style/speed/speaker_boost, rejects continuity fields, and the monthly quota is the real ceiling.',
    licence: 'Subscription; commercial per plan. Output must NOT be redistributed under permissive licences — no 11L audio ships in this repo.',
    cost: '≈$0.22/1k chars (v3); flash_v2_5 half-credit',
    role: 'Hero lines with audio tags; the house narrator ("Battlerap Algorithm", eleven_v3).',
    speedStatic: 'measured 6,420 chars → 55.9 s wall (multilingual_v2, chunked)',
    caps: 'v3 5,000 / multilingual_v2 10,000 / flash_v2_5 40,000 chars per call (real walls 1.1× — undocumented slack). CHUNKED since 2026-07-20: whole story in, one file out.',
    capabilities: ['v3 audio tags — open vocabulary, ~23 enumerated + dozens attested', 'previous_text/next_text prosody continuity (v2 family only, unbilled — verified)', 'text-to-dialogue endpoint: consecutive lines in ONE generation with per-line timestamps (v3, up to 10 voices) — biggest unbuilt quality win', 'voice design API: 3 previews/call, 1 credit/char', '/with-timestamps = free exact alignment on 11L lanes'],
    limitations: ['v3: style/speed/speaker_boost silently ignored (can_use_style:false, still returns 200)', 'stability 1.0 SUPPRESSES tags', 'voice slots 144/160 and cannot be raised — designed voices save as local seeds, never to the account', 'concurrency does NOT queue gracefully: 16 parallel → 6×429 in 145 ms (contradicts their blog)'],
    measured: ['every model\'s enforced wall = exactly 1.1× documented cap (binary search, 3 models)', 'account live: Pro, 982,767 chars/cycle, resets monthly', 'v3 speaks "[whispers]" as 0.14 s of tag; multilingual_v2 reads it ALOUD (1.13 s) — tags are v3-only, gate confirmed'],
    earRuling: 'Narrator = "Battlerap Algorithm" on eleven_v3 (#1), turbo_v2 second — ranked blind.',
  },
  {
    id: 'chatterbox', name: 'Chatterbox (Resemble)', kind: 'voice', tier: 'free · local GPU',
    status: 'gated', grade: 'B',
    gradeWhy: 'Excellent cloning fidelity (+3–7 Hz on clear voices) and the only MIT-clean quality-tier model — but the emotion dial is also a pitch dial (+34–42 Hz in EVERY case), and elderly voices lose their age. Adopted for identity + emotion, gated, elderly stays premium.',
    licence: 'MIT (code + weights). PerTh watermark on by default (removable — decide deliberately).',
    cost: '$0',
    role: 'Candidate third free engine: cloned voices WITH a per-line emotion dial (what Qwen3 clones can\'t do).',
    speedStatic: '5–16 s/line on the 4090; ~4 GB VRAM',
    caps: 'English-only (Turbo); needs its own venv (pins torch 2.6, needs setuptools<81)',
    capabilities: ['clone from ~10 s refs — our actors/ seeds are already the right spec', 'exaggeration knob 0.5–1.0 + [laugh]/[cough] tags on clones'],
    limitations: ['exaggeration raises pitch ~+35 Hz across the board', 'elderly/boundary voices drift out of register (136 Hz male → 168–178 Hz)', 'vendor benchmark claims are vendor-run'],
    measured: ['battery: controls PASS all 4; nola-elder 1/2; liu-xiao 0/2 at the register gate', 'reference length matters: 24 s ref drifted 64 Hz, 10 s trim cut it to 16 Hz', 'pipeline finding: pick the clone window whose median F0 matches the whole clip — the head is often unrepresentative'],
    earRuling: '"Doesn\'t sound elderly anymore, but it sounds like the same person for sure" — identity survives, AGE doesn\'t. Robert preferred exaggeration 1.0 on NOLA.',
  },
  {
    id: 'acestep', name: 'ACE-Step 1.5', kind: 'music', tier: 'free · local GPU',
    status: 'active', grade: 'B-',
    gradeWhy: 'Robert\'s ear: 3/5 — "worth keeping", now the DEFAULT music lane because free beats paid at this quality gap. Docked for the "samey" quality ceiling; community consensus "between Suno 4.5 and 5".',
    licence: 'MIT — code AND weights, both LICENSE files read. (VAE is its own MIT Oobleck, not a Stability inherit.)',
    cost: '$0',
    role: 'Score: underscore beds and stings, 10–600 s in one generation.',
    speedStatic: '8.3 s per 30 s bed warm on the 4090; 845 s first-call model load; cache re-hit 0 ms',
    caps: '10–600 s per call; sidecar keeps ~8 GB VRAM warm',
    capabilities: ['bpm/key_scale/time_signature control', 'instrumental law: caption + [Instrumental] lyrics pinned', 'deterministic seeds from the content key'],
    limitations: ['quality ceiling — "slightly samey" (near-feature for underscore)', 'first request after install can stall minutes downloading 8.4 GB'],
    measured: ['two 30 s beds through renderTrack(): exact duration, −17.5/−20.7 dB mean, both gates PASS'],
    earRuling: '"Worth keeping" — 3/5. Default lane by that ruling.',
  },
  {
    id: 'eleven-music', name: 'ElevenLabs Music', kind: 'music', tier: 'paid · API',
    status: 'active', grade: 'B',
    gradeWhy: 'The verified-licence paid lane; now guarantees instrumental via force_instrumental instead of asking nicely. Opt-in since the free lane was ruled good enough.',
    licence: 'Music Commercial Rights table: audiobooks allowed (not film/TV/radio/games). ⚠ Starter→Pro plans are "Individual Use Only" — a COMPANY product needs Business/Enterprise tier. Training data genuinely licensed (Merlin + Kobalt deals).',
    cost: '≈$0.15/min via API',
    role: 'Premium underscore when a book demands it (DRAMATIS_MUSIC=elevenlabs).',
    speedStatic: 'seconds per track via API',
    caps: 'music_length_ms up to 600,000 (we clamp 300k); seed+prompt together → 422',
    capabilities: ['force_instrumental: true — guaranteed no vocals', 'model_id music_v2 (we were silently getting v1 before)'],
    limitations: ['costs money in a slot the free lane now covers by default'],
    measured: [],
    earRuling: null,
  },
  {
    id: 'clap', name: 'LAION-CLAP + CC0 corpus', kind: 'sfx-retrieval', tier: 'free · local',
    status: 'active', grade: 'A-',
    gradeWhy: 'Measured 73.3% R@1 / 88.3% R@3 on our own shipped corpus with FSD50K ground truth — a genuinely strong retrieval result (random is <1%). Docked for the ranking incidents that needed hand rules.',
    licence: 'CLAP Apache-2.0; corpus CC0 (2,399) + CC-BY (1,697, credits auto-generated) + 10 house clips.',
    cost: '$0',
    role: 'Sound effects: text cue → ranked corpus clips → human approves.',
    speedStatic: 'query <1 s; full 4,096-clip index build ≈ minutes on GPU',
    caps: 'corpus 4,096 clips (was 2,399; +71% via CC-BY, zero download); full ~19.9k CC0 needs the 24 GB dev split',
    capabilities: ['deterministic chunk+mean-pool embeddings (rand-crop bug FIXED — 30% of index was nondeterministic)', 'vocal-caption guard, noun-overlap re-rank, house +0.08 bonus, per-cue approval'],
    limitations: ['ranking quality decides everything — footsteps-as-barefoot and city-night-as-helicopter both happened', 'corpus not in repo (~7 GB built locally, no fetch script yet)'],
    measured: ['R@1 73.3 / R@3 88.3 / R@10 96.7 / MRR .825 over 60 classes (scripts/retrieval-bench.py)'],
    earRuling: 'FSD50K door knock: "really good."',
  },
  {
    id: 'glap', name: 'GLAP (Xiaomi)', kind: 'sfx-retrieval', tier: 'free · local',
    status: 'rejected', grade: 'F',
    gradeWhy: 'REJECTED BY MEASUREMENT: 28.3% R@1 vs the incumbent\'s 73.3% on our corpus — the paper\'s "FSD50K 40.9 vs 21.5" is multi-label classification, not retrieval, and our bench is the task we actually run. Padding confound tested first; ordering never close to reversing.',
    licence: 'Apache-2.0 (fine — quality was the failure).',
    cost: '$0',
    role: 'Was the paper-recommended CLAP upgrade. The standing bench exists so nobody re-adopts it on the same tables.',
    speedStatic: '—',
    caps: '16 kHz input; sigmoid-trained scores (thresholds not comparable to CLAP\'s)',
    capabilities: ['multilingual retrieval'],
    limitations: ['encode_text broken on GPU out of the box (tokens hardcoded to CPU)'],
    measured: ['21.7% R@1 padded / 28.3% native-length vs 73.3% incumbent'],
    earRuling: null,
  },
  {
    id: 'qwen3-fa', name: 'Qwen3-ForcedAligner-0.6B', kind: 'alignment', tier: 'free · local',
    status: 'active', grade: 'A-',
    gradeWhy: 'Word-exact cue placement is what makes "the door slams on the word door" true. CPU fallback since 2026-07-20; failures degrade to line-start placement instead of killing the render.',
    licence: 'Apache-2.0.',
    cost: '$0',
    role: 'Word onsets for SFX placement; future read-along export.',
    speedStatic: '~80 ms/line on GPU; slower but working on CPU (float32)',
    caps: '~1.5 GB VRAM on GPU',
    capabilities: ['per-line cached like everything else', 'multilingual'],
    limitations: ['an enhancement, not a gate — silent degradation is by design and logged'],
    measured: [],
    earRuling: null,
  },
  {
    id: 'seed-audio', name: 'Seed Audio 1.0 (ByteDance)', kind: 'set-piece', tier: 'paid · API (fal)',
    status: 'research', grade: '—',
    gradeWhy: 'Premise VERIFIED against the live fal schema (2026-07-20): one endpoint really does produce dialogue+SFX+music as one balanced track, with reference-voice anchors — so company actors can star in trailers. Ungraded until a live probe of the claims our batteries never test (children, distress). No stems, so it can never replace assembly for books.',
    licence: 'fal "Commercial use" badge (pass) — but output ownership is unstated in ToS and Seed-TTS lineage carries watermarking. Flag before a shipped commercial trailer.',
    cost: '$0.1875/min of output (~$0.375 per 2-min set-piece)',
    role: 'Trailers, teasers, produced set-pieces — a PRINT, not a session. Prior set-pieces were ear-ruled "amazing".',
    speedStatic: '—',
    caps: '~2 min/generation (no duration param); prompt ~2,048 chars; audio_urls max 3 × 30 s; NO seed, NO emotion param, NO timestamps — all control is prose',
    capabilities: ['one-pass produced scene (T2A) — confirmed, the headline feature', 'voice anchoring: @Audio1..3 inline, or pre-clone once → speaker_id valid 12 months', 'pitch ±12 semitones, speed/volume 0.5–2', 'elderly voices evidenced in fal\'s own examples'],
    limitations: ['NO stems — cannot duck, fix a word, or master to ACX; you re-generate, not re-mix', 'timing is narrative-only: speaker turns yes, numeric timing no', 'babies/pain/dying: ZERO public evidence either way — needs a ~$1 probe before betting trailers on it', 'image_url and audio_urls are mutually exclusive'],
    measured: [],
    earRuling: '"Seed dance audio a and b — amazing" (2026-07-19, prior probes).',
  },
  {
    id: 'lyra', name: 'Lyria 3 / 3 Pro (Google)', kind: 'music', tier: 'paid · API (Replicate/fal)',
    status: 'rejected', grade: 'C+',
    gradeWhy: 'Evaluated at Robert\'s request (he rates our music 3/5). Two independent evidence sweeps agree. Blind crowd-voted ELO (Artificial Analysis, ~6k samples/board): #4 instrumental / #7 vocals — behind Suno V5.5, V5 AND Mureka V8 on both boards. Real-user consensus, 20+ threads: best-in-class raw FIDELITY, composition "corporate/soulless" — the same "samey" ceiling ACE-Step has, at a price, with a watermark. Structurally wrong for cue-timed beds: no duration parameter ("the only real length control turns out to be how long your lyrics are"), timestamps round to the nearest musical bar, NO seed on Lyria 3 (Lyria 2 had seed + negative_prompt — both dropped), vocals by default unless constrained (breaks the cast-only law), and moderation silently substitutes lyrics while still burning credits. The fidelity edge buys none of that back.',
    licence: 'LIKELY commercial-clear (Google preview terms carve Lyria out by name) but no indemnity while preview, and reseller pass-through undocumented. SynthID is baked into the spectrum — "the only way to get rid of it is to completely recreate your song".',
    cost: '$0.04 per 30 s, $0.08 Pro (~3 min)',
    role: 'Rejected for underscore. Honourable mention: users get genuinely impressive INSTRUMENTAL cinematic one-offs out of Pro (an Expedition-33-style cue fooled a fan), so it could serve as a hand-picked stinger source — never an automated lane.',
    speedStatic: 'mid-pack in a 5-model API race (ElevenLabs fastest at 16–32 s/track)',
    caps: '30 s (Fast) / ~3 min (Pro); 20 generations/day on the consumer tier; no duration param; no audio upload; stems only on the FlowMusic surface',
    capabilities: ['top-tier fidelity and instrument separation ("Suno sounded like it was played inside a drum kit compared to Google")', 'pristine vocal stems (irrelevant to us — we forbid vocals)', 'prompt adherence on literal instructions ("guitar fades in at the intro" honoured where Suno missed it)'],
    limitations: ['auto-generates vocals/lyrics by default — direct conflict with the cast-are-the-only-voices law', 'no duration control of any kind; timestamps round to the nearest bar (bad for scene sync)', 'no seed on Lyria 3 — cross-cue reproducibility unaddressed ("results vary between calls, even with the same prompt" — Google\'s own docs)', 'SynthID in the spectrum, not strippable', 'narrow training: "African music? Nope. Latin American? Very bad." — genre blending collapses to pop', 'silent lyric substitution that still burns credits', 'single-turn only: no iterative editing, no stems, no inpainting'],
    measured: [],
    earRuling: 'Robert rates current music 3/5 — this was the "is there better" check. Answer: not for our shape of work.',
  },
];
